This is makeindex, version 2.16 [MiKTeX 25.3].
Scanning style file ./Chapter1.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Chapter1.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file Chapter1.acr....done (7 lines written, 0 warnings).
Output written in Chapter1.acr.
Transcript written in Chapter1.alg.
